/*
 * generated by Xtext
 */
package org.chw.game.ide.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractProtoValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.chw.game.ide.proto.ProtoPackage.eINSTANCE);
		return result;
	}
}
