/*
 * generated by Xtext
 */
package org.chw.game;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CfgRuntimeModule extends org.chw.game.AbstractCfgRuntimeModule {

}
