/*
* generated by Xtext
*/
package org.chw.game;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CfgStandaloneSetup extends CfgStandaloneSetupGenerated{

	public static void doSetup() {
		new CfgStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

