/**
 * generated by Xtext
 */
package org.chw.game.validation;

import org.chw.game.validation.AbstractCfgValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class CfgValidator extends AbstractCfgValidator {
}
