/*
 * generated by Xtext
 */
package org.chw.game.formatting;

import com.google.inject.Inject;
import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.chw.game.services.CfgGrammarAccess;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#formatting on how and
 * when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an
 * example
 */
public class CfgFormatter extends AbstractDeclarativeFormatter
{

	@Inject
	private CfgGrammarAccess grammarAccess;

	@Override
	protected void configureFormatting(FormattingConfig c)
	{
		c.setLinewrap(2).after(grammarAccess.getTypeRule());

		c.setLinewrap().before(grammarAccess.getFieldRule());
		c.setLinewrap(2).after(grammarAccess.getFieldRule());

		c.setLinewrap().after(grammarAccess.getCOMMENTRule());

		c.setLinewrap().before(grammarAccess.getC_BRACE_LRule());
		c.setLinewrap().before(grammarAccess.getC_BRACE_RRule());

		c.setIndentationIncrement().after(grammarAccess.getC_BRACE_LRule());
		c.setIndentationDecrement().before(grammarAccess.getC_BRACE_RRule());
	}
}
