/*
* generated by Xtext
*/
package org.chw.game.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.chw.game.services.CfgGrammarAccess;

public class CfgParser extends AbstractContentAssistParser {
	
	@Inject
	private CfgGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.chw.game.ui.contentassist.antlr.internal.InternalCfgParser createParser() {
		org.chw.game.ui.contentassist.antlr.internal.InternalCfgParser result = new org.chw.game.ui.contentassist.antlr.internal.InternalCfgParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getXML2Access().getAlternatives_0(), "rule__XML2__Alternatives_0");
					put(grammarAccess.getXML2Access().getAlternatives_1(), "rule__XML2__Alternatives_1");
					put(grammarAccess.getTypeAccess().getAlternatives_5(), "rule__Type__Alternatives_5");
					put(grammarAccess.getTypeNameAccess().getAlternatives(), "rule__TypeName__Alternatives");
					put(grammarAccess.getXML2Access().getGroup(), "rule__XML2__Group__0");
					put(grammarAccess.getXML2Access().getGroup_0_0(), "rule__XML2__Group_0_0__0");
					put(grammarAccess.getXML2Access().getGroup_0_1(), "rule__XML2__Group_0_1__0");
					put(grammarAccess.getInputDefAccess().getGroup(), "rule__InputDef__Group__0");
					put(grammarAccess.getPackDefAccess().getGroup(), "rule__PackDef__Group__0");
					put(grammarAccess.getTypeAccess().getGroup(), "rule__Type__Group__0");
					put(grammarAccess.getEnterAccess().getGroup(), "rule__Enter__Group__0");
					put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
					put(grammarAccess.getFieldMetaAccess().getGroup(), "rule__FieldMeta__Group__0");
					put(grammarAccess.getFieldMetaAccess().getGroup_2(), "rule__FieldMeta__Group_2__0");
					put(grammarAccess.getFieldMetaAccess().getGroup_2_1(), "rule__FieldMeta__Group_2_1__0");
					put(grammarAccess.getFieldMetaAccess().getGroup_2_1_1(), "rule__FieldMeta__Group_2_1_1__0");
					put(grammarAccess.getPackNameAccess().getGroup(), "rule__PackName__Group__0");
					put(grammarAccess.getPackNameAccess().getGroup_1(), "rule__PackName__Group_1__0");
					put(grammarAccess.getXML2Access().getInputAssignment_0_0_0(), "rule__XML2__InputAssignment_0_0_0");
					put(grammarAccess.getXML2Access().getPackAssignment_0_0_1(), "rule__XML2__PackAssignment_0_0_1");
					put(grammarAccess.getXML2Access().getPackAssignment_0_1_0(), "rule__XML2__PackAssignment_0_1_0");
					put(grammarAccess.getXML2Access().getInputAssignment_0_1_1(), "rule__XML2__InputAssignment_0_1_1");
					put(grammarAccess.getXML2Access().getPackAssignment_0_2(), "rule__XML2__PackAssignment_0_2");
					put(grammarAccess.getXML2Access().getInputAssignment_0_3(), "rule__XML2__InputAssignment_0_3");
					put(grammarAccess.getXML2Access().getTypesAssignment_1_0(), "rule__XML2__TypesAssignment_1_0");
					put(grammarAccess.getXML2Access().getCommAssignment_1_1(), "rule__XML2__CommAssignment_1_1");
					put(grammarAccess.getInputDefAccess().getCommentAssignment_0(), "rule__InputDef__CommentAssignment_0");
					put(grammarAccess.getInputDefAccess().getInputCHARAssignment_1(), "rule__InputDef__InputCHARAssignment_1");
					put(grammarAccess.getInputDefAccess().getUrlAssignment_2(), "rule__InputDef__UrlAssignment_2");
					put(grammarAccess.getPackDefAccess().getCommentAssignment_0(), "rule__PackDef__CommentAssignment_0");
					put(grammarAccess.getPackDefAccess().getPackCHARAssignment_1(), "rule__PackDef__PackCHARAssignment_1");
					put(grammarAccess.getPackDefAccess().getPackAssignment_2(), "rule__PackDef__PackAssignment_2");
					put(grammarAccess.getTypeAccess().getCommentAssignment_0(), "rule__Type__CommentAssignment_0");
					put(grammarAccess.getTypeAccess().getEnterAssignment_1(), "rule__Type__EnterAssignment_1");
					put(grammarAccess.getTypeAccess().getPrefixAssignment_2(), "rule__Type__PrefixAssignment_2");
					put(grammarAccess.getTypeAccess().getNameAssignment_3(), "rule__Type__NameAssignment_3");
					put(grammarAccess.getTypeAccess().getFieldsAssignment_5_0(), "rule__Type__FieldsAssignment_5_0");
					put(grammarAccess.getTypeAccess().getCommAssignment_5_1(), "rule__Type__CommAssignment_5_1");
					put(grammarAccess.getEnterAccess().getPrefixAssignment_1(), "rule__Enter__PrefixAssignment_1");
					put(grammarAccess.getEnterAccess().getRootPathAssignment_3(), "rule__Enter__RootPathAssignment_3");
					put(grammarAccess.getFieldAccess().getCommentAssignment_0(), "rule__Field__CommentAssignment_0");
					put(grammarAccess.getFieldAccess().getMetaAssignment_1(), "rule__Field__MetaAssignment_1");
					put(grammarAccess.getFieldAccess().getTypeAssignment_2(), "rule__Field__TypeAssignment_2");
					put(grammarAccess.getFieldAccess().getFieldNameAssignment_3(), "rule__Field__FieldNameAssignment_3");
					put(grammarAccess.getFieldAccess().getNodePathAssignment_5(), "rule__Field__NodePathAssignment_5");
					put(grammarAccess.getFieldTypeAccess().getTypeAssignment(), "rule__FieldType__TypeAssignment");
					put(grammarAccess.getFieldMetaAccess().getPrefixAssignment_1(), "rule__FieldMeta__PrefixAssignment_1");
					put(grammarAccess.getFieldMetaAccess().getParamsAssignment_2_1_0(), "rule__FieldMeta__ParamsAssignment_2_1_0");
					put(grammarAccess.getFieldMetaAccess().getParamsAssignment_2_1_1_1(), "rule__FieldMeta__ParamsAssignment_2_1_1_1");
					put(grammarAccess.getFieldMetaKeyAccess().getFieldNameAssignment(), "rule__FieldMetaKey__FieldNameAssignment");
					put(grammarAccess.getOtherComentAccess().getCommAssignment(), "rule__OtherComent__CommAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.chw.game.ui.contentassist.antlr.internal.InternalCfgParser typedParser = (org.chw.game.ui.contentassist.antlr.internal.InternalCfgParser) parser;
			typedParser.entryRuleXML2();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS" };
	}
	
	public CfgGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CfgGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
