/*
* generated by Xtext
*/
package org.chw.game.ide;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ProtoStandaloneSetup extends ProtoStandaloneSetupGenerated{

	public static void doSetup() {
		new ProtoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

