/*
 * generated by Xtext
 */
package org.chw.game.ide.ui;

import org.chw.game.ide.ui.folder.ProtoFolding;
import org.chw.game.ide.ui.highlight.ProtoHighlight;
import org.chw.game.ide.ui.highlight.ProtoHighlightingCalculator;
import org.chw.game.ide.ui.highlight.ProtoLexerHighlighting;
import org.chw.game.ide.ui.hyperlink.ProtoHyperLinkHelper;
import org.chw.game.ide.ui.hyperlink.ProtoLoationInFileProvider;
import org.chw.game.ide.ui.textHover.ProtoHoverProvider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;
import org.eclipse.xtext.resource.ILocationInFileProvider;
import org.eclipse.xtext.ui.editor.folding.IFoldingRegionProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ProtoUiModule extends org.chw.game.ide.ui.AbstractProtoUiModule
{
	public ProtoUiModule(AbstractUIPlugin plugin)
	{
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration()
	{
		return ProtoHighlight.class;
	}

	public Class<? extends IOutputConfigurationProvider> bindIOutputConfigurationProvider()
	{
		return OutputConfig.class;
	}

	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindLexerProvider()
	{
		return ProtoLexerHighlighting.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator()
	{
		return ProtoHighlightingCalculator.class;
	}

	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider()
	{
		return ProtoHoverProvider.class;
	}

	public Class<? extends IFoldingRegionProvider> bindIFoldingRegionProvider()
	{
		return ProtoFolding.class;
	}

	public Class<? extends ILocationInFileProvider> bindILocationInFileProvider()
	{
		return ProtoLoationInFileProvider.class;
	}

	@Override
	public Class<? extends org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper> bindIHyperlinkHelper()
	{
		return ProtoHyperLinkHelper.class;
	}

	// contributed by
	// org.eclipse.xtext.generator.builder.BuilderIntegrationFragment
	public Class<? extends org.eclipse.xtext.ui.editor.IXtextEditorCallback> bindIXtextEditorCallback()
	{
		return org.eclipse.xtext.ui.editor.IXtextEditorCallback.NullImpl.class;
	}
}
