/**
 * generated by Xtext
 */
package org.chw.game.ui.contentassist;

import org.chw.game.ui.contentassist.AbstractCfgProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class CfgProposalProvider extends AbstractCfgProposalProvider {
}
