/*
 * generated by Xtext
 */
package org.chw.game.ide.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.chw.game.ide.ui.internal.ProtoActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProtoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ProtoActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ProtoActivator.getInstance().getInjector(ProtoActivator.ORG_CHW_GAME_IDE_PROTO);
	}
	
}
