/*
 * generated by Xtext
 */
package org.chw.game.ui.outline;

import org.chw.game.cfg.Field;
import org.chw.game.cfg.Type;
import org.chw.game.cfg.XML2;
import org.eclipse.swt.graphics.Image;
import org.eclipse.xtext.ui.IImageHelper;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;

import com.google.inject.Inject;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
public class CfgOutlineTreeProvider extends org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider
{
	@Inject
	private IImageHelper imgHelper;
	
	protected void _createNode(DocumentRootNode parent, XML2 model)
	{
		if (model.getTypes().size() > 0)
		{
			for (Type element : model.getTypes())
			{
				createNode(parent, element);
			}
		}
	}

	// type
	protected Image _image(Type type)
	{
		return imgHelper.getImage("typeIcon.gif");
	}
	
	protected Object _text(Type type)
	{
		return type.getName();
	}

	protected boolean _isLeaf(Type type)
	{
		return false;
	}

	protected void _createChildren(IOutlineNode parent, Type type)
	{
		for (Field field : type.getFields())
		{
			createNode(parent, field);
		}
	}

	// field
	protected Image _image(Field type)
	{
		return imgHelper.getImage("fieldIcon.gif");
	}
	
	protected Object _text(Field field)
	{
		return field.getFieldName();
	}

	protected boolean _isLeaf(Field field)
	{
		return true;
	}
}
