/*
* generated by Xtext
*/
package org.chw.game.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.chw.game.services.CfgGrammarAccess;

public class CfgParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CfgGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected org.chw.game.parser.antlr.internal.InternalCfgParser createParser(XtextTokenStream stream) {
		return new org.chw.game.parser.antlr.internal.InternalCfgParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "XML2";
	}
	
	public CfgGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CfgGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
